### PR TITLE
Hotfix #1198 #1014 on tag 3.0.5

### PR DESCRIPTION
**Pull request by adamcavendish**
Hi, this pr is not meant to be merged.

The freezing issues #1198 and #1014 are fixed in HEAD but not in 3.0.x. Because of ubuntu's package update policy, the package `guake` in ubuntu repository may always be broken on 18.04 (stable version).

Issue is also mentioned in https://bugs.launchpad.net/ubuntu/+source/guake/+bug/1760621 .

It is simply fixed by following steps to deliver 3.0.6 fixing these issues.
1. checkout to tag 3.0.5
2. edit line 1420 in `guake/guake_app.py` to remove indentation of `self.delete_tab(self.notebook.page_num(widget), kill=False, prompt=False)`
3. create a hotfix branch, commit and release 3.0.6

It'll help deliver a working guake in ubuntu 18.04. Thx.

### CODE REVIEW

**Comment by gsemet** [comment]
you mean, since the package is no more maintained, ubuntu cannot package 3.4+, so releasing a minor fix as 3.0.6 would be still be packaged automaticaly in ubuntu?

**Comment by gsemet** [comment]
Look like it is still being maintained, simply 3.4.0-1 is not backported to 18.04: https://launchpad.net/ubuntu/+source/guake

**Comment by adamcavendish** [comment]
It is, but because of policy only patched version (3.0.x) can be packaged for update after major versions of ubuntu is released. Long term support version 18.04 (named Bionic Beaver) freezes.guake at version 3.0 and therefore it cannot get 3.4.0 even till the end of life. As a result, releasing patched versions do help. Thx.

**Comment by adamcavendish** [comment]
Ping collaborators. Due to the ubuntu package policy issue, we still are looking forward to 3.0.6. Please spare 5 mins to release a patched version.

**Comment by ulidtko** [comment]
@adamcavendish done in branch `ubuntu-lts-hotfix`, thanks for clear explanation.

@gsemet hi, what's the current workflow to release 3.0.6 ?

**Comment by gsemet** [comment]
I am working on it

**Comment by gsemet** [comment]
[3.0.6](https://github.com/Guake/guake/releases/tag/3.0.6) released :)

**Comment by ulidtko** [comment]
@adamcavendish hey, could you please shed some light onto the Ubuntu release process, LTS and in general?..

We've done the hotfix release, 3.0.6 as you requested, but on repository aggregators like [here][pkgs.org] one can see 3.0.5 is still in wide use (also 0.8.8, woah).

In a nutshell... whom can we ping for repackaging an Ubuntu LTS update? :smiley: 

[pkgs.org]: https://pkgs.org/download/guake

**Comment by gsemet** [comment]
For me, I do not see the reason why Ubuntu/Debian would stick to minor releases. Lot of software do not follow semver, so their update version is pretty much meaningless from a system point of view.
My guake still runs fine on Ubuntu 16.04 (it is meant to), even in version 3.6.
So for me the real answer to all these bugs is: update to v3.6.

**Comment by adamcavendish** [comment]
I updated the thread in https://bugs.launchpad.net/ubuntu/+source/guake/+bug/1760621/ and it seems that they're not acting quick enough.

**Pull request closed without merging**
