### PR TITLE
 fix data path in paths.py

### PR DESCRIPTION
**Pull request by MahaGamal**
Issue on Guake Terminal 3.4.0

I tracked it down to `ab7b44a`.
 If I undo this change, guake will start.

### CODE REVIEW

**Comment by gsemet** [comment]
How did you installed guake?

**Comment by MahaGamal** [comment]
Using Make or pip3, I had same problem with data path until editing path it’s working fine

**Comment by aichingm** [comment]
How did your paths look before and after the change?

**Comment by ulidtko** [comment]
This isn't a good fix, I give my **Don't merge** here. :-1: 

The proper way is to use `pkg_resources.get_resource_filename()` instead of the hacking around `__file__`. The `paths.py.in` even imports that function — but doesn't use it.

See e.g. [this stackoverflow](https://stackoverflow.com/questions/39104/finding-a-file-in-a-python-module-distribution).

**Comment by ulidtko** [comment]
As a side note: patches like this should be **rebased** onto the latest master, not merge it in.

**Comment by gsemet** [comment]
I agree to not merge that, but I would like to ditch pkg_resource at one point. The real solution is to use importlib_resource library instead.

**Pull request closed without merging**
