### PR TITLE
Remove GDK_BACKEND to force x11

### PR DESCRIPTION
**Pull request by Davidy22**
After much feedback from the wayland users who don't want Guake to run in xwayland

Created in response to much feedback from #1934 and other related issues

### CODE REVIEW

**Comment by VitalyAnkh** [comment]
Could we merge this?

**Comment by mlouielu** [comment]
> Could we merge this?

Let me take some time on this

It seems more suitable with a revert, but I cannot access to my laptop now.

**Review by mlouielu — CHANGES_REQUESTED** [review]
I would like to have another discussion in #1934, which I proposed not to remove force x11 backend as default, but add `GUAKE_ENABLE_WAYLAND=1` as an alternative way to use `GDK_BACKEND=wayland`.

**Comment by Davidy22** [comment]
Closing since this'll be supplanted with an option

**Pull request closed without merging**
