### PR TITLE
Guake3 rework build system

### PR DESCRIPTION
**Pull request by adogyf**

### CODE REVIEW

**Comment by Stibbons** [comment]
yes, not ready yet. But I still have some work to do to support virtualenv with guake. I really hate having to install dependencies on the system.

**Comment by adogyf** [comment]
Sorry for that. I'm also trying to make install from setup.py to env.

19 paź 2017 21:12 "Gaetan Semet" <notifications@github.com> napisał(a):

**Comment by Stibbons** [comment]
I think I can have something by today :)

**Comment by adogyf** [comment]
Ok, thanks

20 paź 2017 10:32 "Gaetan Semet" <notifications@github.com> napisał(a):

**Comment by Stibbons** [comment]
I have merged my pr in your branch. I hope this can land to master soon, even if all features are not ported yet (and we drop the imgbg feature, it's pointless)

**Pull request closed without merging**
