### PR TITLE
Add DeepSource config file for static analysis

### LINKED ISSUE #1787: Some code quality issues found in guake
I have been using guake for a long time and so I thought of trying a code quality checkup. I forked this repo and thus ran a [DeepSource](https://deepsource.io) analysis on my [forked repo](https://github.com/pnijhara/guake/tree/pnijhara-patch-1).
The best part was there were not more than 25 issues found.
- Antipatterns: 8
- Security Issues: 17

Quite a less number, however, can be fixed in no time.
You can find the detailed report here &rarr; https://deepsource.io/gh/pnijhara/guake/issues/?category=recommended

Some of the issues can be fixed in a single click using DeepSource Autofix tool.

Do let me know which of the issues are solvable. I would love to send a patch with some fix.

I have also added a DeepSource config file `.deepsource.toml` in my forked repo to let DeepSource run analysis on it. The file can be found [here](https://github.com/pnijhara/guake/blob/pnijhara-patch-1/.deepsource.toml).

### PR DESCRIPTION
**Pull request by pnijhara**
fix #1787 
This PR adds a `.deepsource.toml` file to the Guake codebase.
After merging you can signup at [DeepSource](https://deepsource.io) to let DeepSource analyse this project. Once, analysis is completed, DeepSource will automatically analyze every new change to Guake on every PR.

You can follow [these](https://deepsource.io/docs/quickstart/create-account.html#connect-github) steps for creating an account on DeepSource.
For more details refer to docs &rarr; https://deepsource.io/docs
Do let me know if you need any help.

### CODE REVIEW

**Comment by gsemet** [comment]
thanks, but I don't see the added value for that?

**Comment by pnijhara** [comment]
@gsemet could you be more specific?

**Comment by gsemet** [comment]
what does this service do compared to what we have already

**Comment by ulidtko** [comment]
> what we have already

image

> image

@gsemet would you be so kind to answer me here? https://github.com/Guake/guake-website/pull/10#issuecomment-660948304

**Comment by gsemet** [comment]
sure sure, if someone want to take over the site and even guake MR that's not a probl ! Contact me directly at gaetan@xeberon.net

**Comment by gsemet** [comment]
not sure if deepsource will fix automatically the issues... but sure, if someone want to take the time to fix all issues here I would be glad. Too much stuff to do, baby to take care, and not working primarily on linux anymore, that's difficult for me

**Comment by ulidtko** [comment]
> sure sure, if someone want to take over the site and even guake MR that's not a probl ! Contact me directly at [gaetan@xeberon.net](mailto:gaetan@xeberon.net)

Excuse me, I'm not "someone". I'm one of previous Guake maintainers.

And I don't intend to "take over" anything. I just want to make sure that the project carries on and keeps existing and being taken care of, even when the current maintainers are not in their best of times. We've been in that exact situation before.

I'll drop you a mail. Take care.

**Comment by gsemet** [comment]
sorry for the misunderstanding.

**Comment by pnijhara** [comment]
So unprofessional!

**Comment by gsemet** [comment]
Sorry, pull request is very old, and I still don’t understand what it does.

**Comment by Davidy22** [comment]
Saw this while going back through open issues, changes are detached enough from the rest of the codebase that this being old shouldn't be a huge blocker to getting this to work. Need to get my CI pr merged first though, as I don't have power to merge with failing checks.

**Comment by pnijhara** [comment]
Thanks, @Davidy22 
I waited for a very long time to get this merged but someone closed the PR without proper comments.

**Comment by Davidy22** [comment]
I can't merge if you try to reinvoke build with new commits right now, my CI updates are still unmerged and waiting so the main repo is still on the old travis build that hangs and failed before it started hanging. Hopefully won't take too long for it to get in the repo, then you should be able commit with a passing build and I'll be able to merge. I can try this out in the meantime, getting late today, I'll give it a spin in the morning and get back with thoughts on the output

**Comment by Davidy22** [comment]
Alright I finally put aside the time to run it, I see some fine recommendations, a decent chunk was redundant with things the linter we already caught that I'm going to have fixed in my CI update. It found a few extra things though, I didn't try making the changes to see if it was recommending breaking changes but most of it seemed pretty low impact. I did notice while signing up that this is a whole extra service, the whole idea of the moving away from travis thing that I've been doing was because they made changes that broke our CI and I'd prefer a static analyser that could be run entirely within github if possible, reduce the number of services we depend on.

**Review by Davidy22 — CHANGES_REQUESTED** [review]
I've fixed CI so now we have a github actions config file. Given that this will probably be part of the CI pipeline, I'd like to see something added to actions to invoke deepsource as part of CI, and then a second commit to make the codebase pass CI. Then I'll check out your branch post-fixes and make sure it didn't get uglier and it didn't break anything and we can look at folding this in.

Once you're done ideally your incoming commit log should be squashed down to a commit that enables deepsource as part of CI, then a second commit with a passing build.

**Comment by srijan-deepsource** [comment]
Hey @Davidy22: Chiming in here — DeepSource does not integrate with your CI tool, and is an independent service. We have a GitHub app, which when installed activates analyses on your codebase. Going forward, it will add GitHub checks to raise code quality issues on every incoming commit and PRs.
This is not going to affect your CI workflow at all.

Here's how a pull request looks with DeepSource checks enabled: https://github.com/deepsourcelabs/demo-python/pull/231
I hope this helps!

//cc @pnijhara

**Comment by Davidy22** [comment]
Word, I wasn't expecting to see a dev from the service itself in here. Well, I don't have enough permissions on the repo to install any of the shiny toys on github through the repository settings, and I probably shouldn't approve and merge this config file without also flipping that switch in the settings so I'm going to have to either defer to someone who can do that or wait until I have that power to come back and take a look at this again.

**Comment by gsemet** [comment]
I am so sorry not to understand what deep source does, but it seems only a nice UI on top of pylint, mypy,.. maybe others.

i can enable these checks, but we already do these check in CI and on the developer environment with “make style” and “make check”.

I merge and enable the plugin, let’s see what happens

**Comment by Davidy22** [comment]
I would assume that the first effect of this is going to be a failed build because of deepsource finding things it wants us to fix, so I'll have a pr to fix that in a little bit once it's done.

**Comment by Davidy22** [comment]
Huh, the build passes. I clicked through and it looks like it [still has some things to say about our code](https://deepsource.io/gh/Guake/guake/run/031fbb65-23e3-45b9-9861-52fdfb7aea36/python/), but at least we still have the green check. I guess this only turns red if someone tries to submit code that creates new issues? Well, I'll still get to cleaning up the moans from this thing.

**Comment by gsemet** [comment]
For time being, we can keep it non mandatory until all remarks are fixes or dismissed.
Let’s open a technical debt and reimburse it when possible, probably in various effort.

**Pull request merged**
