### PR TITLE
Add save/restore tabs function

### PR DESCRIPTION
**Pull request by mlouielu**
Hi all, I make a simple version of save/restore tabs function into guake

You can test it with right click on the notebook context menu, it will show up "Save Tabs" & "Restore Tabs" menu item for you to use it.

Since I'm not that familiar to gtk and guake code, there has some issue need to resolved:

1. Currently, it will only save/restore pages directory and its label text, inside the `TerminalBox`, the split will not be saved, should we deal with it? (since I'm not really sure on this)
2. It should add hotkey (accel-key?) for save-tabs and restore-tabs
3. Did guake have some config folder in `.config`?  Currently, the tabs config file default output will be `.guake_tabs.json`, it definitely have some better place and name for it.
4. Cont. previous, the tabs config file output name should be configurable? (again, I'm not familiar with the gtk config stuff :((  )

thanks.

ref: #114

### CODE REVIEW

**Comment by gsemet** [comment]
Yes, that looks cool :) I like the use of ~/.config/guake/session.json.
Accelerator would be cool but this can wait.

Does it restore automatically upon start ?

**Comment by mlouielu** [comment]
So for the tabs config file, it will need to ensure within `XDG_CONFIG_HOME`, maybe a new dependency on `pyxdg` to deal with it

Restore automatically upon start can be made, but I'll prefer to let user choice (just like the browser), and probably auto-save (when changing name / add tab ..etc)

Maybe we can use the desktop notification just like when the guake startup?

And last, for the security issue, did the label text and directory path have been sanitized when accepting the input?

**Comment by gsemet** [comment]
That’s fine for me for the new dep.
You can add a notification that’s a good idea.

There is no sanitation of the text, sadly.

**Comment by gsemet** [comment]
Look great to me. Let’s merge

**Comment by mlouielu** [comment]
@gsemet 6 years issue done! Hooray!

**Pull request merged**
