### PR TITLE
Proposed new layout for the pref dialog

### PR DESCRIPTION
**Pull request by amivaleo**
I submit this so to propose a new gui for the preferences dialog.

I hope someone can take a look at it and try to hook the gui with the code, maybe @Davidy22 could...? I'd be glad to learn how to do that, but I need someone who wants to show me a few examples and teach me a couple of practical things.

### CODE REVIEW

**Comment by Davidy22** [comment]
Just grabbed and loaded it up to take a look and the first impression is it's very tall, like it doesn't fit on my screen, so it probably needs a scrollbar. Could maybe be split into more tabs too, there's some more space at the top for them. Could we get that shiny new tab style that gnome's been pushing, the one that's in glade, the sort of round pill shaped thing? Also the general tab has a lot of empty space at the bottom, because this window is fixed size I presume. I'll hook up a button when I get the time to look at it, just some aesthetic/usability things I noticed for now.

**Comment by mlouielu** [comment]
Could you post some screenshots?

**Comment by Davidy22** [comment]
There's some screenshots in #1618 where this was proposed that are still fairly accurate, but you really need to check the branch out and just try it to get the full impression

**Comment by amivaleo** [comment]
> Just grabbed and loaded it up to take a look and the first impression is it's very tall, like it doesn't fit on my screen, so it probably needs a scrollbar. Could maybe be split into more tabs too, there's some more space at the top for them. Could we get that shiny new tab style that gnome's been pushing, the one that's in glade, the sort of round pill shaped thing? Also the general tab has a lot of empty space at the bottom, because this window is fixed size I presume. I'll hook up a button when I get the time to look at it, just some aesthetic/usability things I noticed for now.

You're right. Consider that I used glade primarily so to provide some mockup. And that mockup is also a bit old. I would have used a different style if I have done it more recently.
So, of course I can add scrollbars and also reshape the headerbar so to host linked buttons (which are the "pill-shaped" things you mean ;) ). However, the incoming trend is to get rid of button borders. Anyway, I remember that the HIGs suggest to avoid putting too many buttons in such manner, and try a different widget (tabs) if possible. So, the choice is driven by how many buttons/tabs should stay in the preferences. And that is something that requires some reasoning.

**Comment by Davidy22** [comment]
No button borders sounds like it could take some getting used to. For the tab count, I'd say we want to at least fill that tab bar, having empty space to the left of the tabs we have while people have to scroll down in the tabs that we kept means we could have filled that space and reduced the amount of scrolling needed.

**Comment by gsemet** [comment]
this PR needs rebase.

**Comment by Davidy22** [comment]
Alright, I rebased, fixed a few errors and filled in a few entries so I have some idea of what needs to be done now. Grab a copy of the prefs.glade from the latest master and open that in glade side-by-side next to this new preferences layout, and for every checkbox you'll need to copy general->ID into the toggle button's ID, and signals->GtkToggleButton->toggled->handler into signals->GtkSwitch->activate->handler. There's also some new items in the preferences menu, off the top of my head I remember copy on select, use system default theme, hide tab bar if one tab, and the new background image stuff, and that stuff needs to be in the new preferences layout too. The menu I think won't start actually toggling settings until you reconnect all the IDs and handlers, and we really need the IDs to be correct and matched, it won't work if you just fill in something random to fill some ID fields. Also there's the little reshuffle and scrollbar thing mentioned earlier as well so that this menu will actually fit on people's screens.

**Comment by amivaleo** [comment]
> Alright, I rebased, fixed a few errors and filled in a few entries so I have some idea of what needs to be done now. Grab a copy of the prefs.glade from the latest master and open that in glade side-by-side next to this new preferences layout, and for every checkbox you'll need to copy general->ID into the toggle button's ID, and signals->GtkToggleButton->toggled->handler into signals->GtkSwitch->activate->handler. There's also some new items in the preferences menu, off the top of my head I remember copy on select, use system default theme, hide tab bar if one tab, and the new background image stuff, and that stuff needs to be in the new preferences layout too. The menu I think won't start actually toggling settings until you reconnect all the IDs and handlers, and we really need the IDs to be correct and matched, it won't work if you just fill in something random to fill some ID fields. Also there's the little reshuffle and scrollbar thing mentioned earlier as well so that this menu will actually fit on people's screens.

I see why there's so much restrain from changing the gui. 👀️
I will pay extra attention to the IDs and handlers.

In the meantime, I edited my original "mockup" a bit. Take a look at the attached file. That's the style that I'd like to suggest now
[prefs.zip](https://github.com/Guake/guake/files/7215628/prefs.zip)
Schermata da 2021-09-23 09-20-15

**Comment by gsemet** [comment]
Do you think it would be possible to have a search box to search for a particular item's text a-la MacOS pref panels. This is soooooo useful

**Comment by amivaleo** [comment]
> Do you think it would be possible to have a search box to search for a particular item's text a-la MacOS pref panels? This is soooooo useful

Of course. But that has to be requested in a different thread I presume. It is a feature request more than a redesign. 🤔️

**Comment by amivaleo** [comment]
Ok, I'm done.
I mean, I should be done. I've added all the settings and copied&pasted all the IDs and handlers.

As a first iteration, there will surely be issues. Let me know.

**Comment by mlouielu** [comment]
Some stuff I saw:
1. Not sure why I cannot saw anything in keyboard shortcuts
2. Background image cannot setup
3. seems not work to let config apply (e.g. font didn't change)

After testing with the UI, I'm like original option box more, it is more compact in one page to let me know what option I'm enable or not.

**Comment by amivaleo** [comment]
> 1. Not sure why I cannot saw anything in keyboard shortcuts

I have this very same issue also with the prefs.glade file from the repo. I thought they were inserted using some code that does not belong to glade.

> 2. Background image cannot setup

Same. I just copied&pasted from the glade file in the repo.

> 3. seems not work to let config apply (e.g. font didn't change)

That has to be investigated carefully If...

> After testing with the UI, I like original option box more, it is more compact in one page to let me know what option I'm enable or not.

... This new gui is not rejected. And that decision is up to you devs.

**Pull request closed without merging**
