### PR TITLE
Save/Restore tabs session with terminal split

### LINKED ISSUE #1571: tab save fails on splitted terminal (DualTerminalBox)
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/guake/utils.py", line 82, in wrapper
    g.save_tabs()
  File "/usr/local/lib/python3.5/dist-packages/guake/guake_app.py", line 1162, in save_tabs
    'directory': page.child.terminal.get_current_directory(),
AttributeError: 'DualTerminalBox' object has no attribute 'terminal'
```

### PR DESCRIPTION
**Pull request by mlouielu**
Fix #1571 

Please check for each commit's message.

### CODE REVIEW

**Comment by mlouielu** [comment]
Hold a sec... it is not working on workspace-specific tab sets...

**Comment by mlouielu** [comment]
> Hold a sec... it is not working well on workspace-specific tab sets... (need more manual test on it).
> 
> But I'm pretty sure it works well on signle tab sets Guake.

Solved, it will also lazy restore when switching workspace now.

**Comment by mlouielu** [comment]
A pending commit is to refactor Guake.pending_restore_page_split into notebook. Still need to test on Linux.

**Comment by gsemet** [comment]
That’s very nice from you to handle schéma migration, but I would have just displayed a dlgbox telling user the format has changed and thus he has to rebuild his tabs... but that very good, i do not see major point to discuss ! Thanks very much !

**Pull request merged**
