### PR TITLE
Upgrade logger to version with file:line and logger file

### PR DESCRIPTION
**Pull request by zeusintuivo**
- Add guake.log logger file 
      - Replaces log.* for logger.*
      - Added filename:line to log lines.
      - Helps with issue https://github.com/Guake/guake/issues/1031 by providing a log file

The principle is to have a better way to know which files are from the log are doing what, or failing where. Also have a logger file will help to debug current issues, and have possibility of asking people to upload guake.log file to review.

### CODE REVIEW

**Comment by mlouielu** [comment]
Hi @zeusintuivo, several thing need to discuss before reviewing this PR:

1. In a PR, we want to focus on one feature (if possible), and styling should be put at a separate PR. So,  `docs/source/conf.py` should not be touched.
2. Before introduce a large change, we need to discuss whether there is a need for this first, for example, what is the need to add `file:lineno` before each log?
3. If we have that need, and it introduce so many duplicate code, then we should consider to put it into a module, not copy-paste in all places.
4. As point 3, if I want to introduce these feature, I will do something like:
  1. one commit for adding logging module
  2. one commit that replace old logging handler
  3. one commit for adding `file:lineno` (maybe this can be handle in logging module)

**Comment by zeusintuivo** [comment]
> "1. ....So, docs/source/conf.py should not be touched."

A: This is was "touched" by the linter. The linter changed it. Are you saying that your own chosen linter should be used?


>  "2. Before introduce a large change, we need to discuss whether there is a need for this first, for example, what is the need to add file:lineno before each log?"

A: If read my description, I will quote myself: "The principle is to have a better way to know which files are from the log are doing what, or failing where. Also have a logger file will help to debug current issues" ....is this description not clear enough ?
I find it the current logging a black box that spits random comments at random times, from random places. Have file and line, adds more precision. 


> "3. ... duplicate code,..." 

A: yes I will like that too. Do you have an idea of how to refactor this to reduce the duplicated code? If you can come if the function that will deliver the filename and line number, correctly, I will expend another 6 hours renaming all the logger. functions. 


> "4.... one commit ...." 

A: ...per file ? are you serious.. It has taken 10 hours to this one change, which is ONE FEATURE. This is only adding better logging, that is it. Any other "files" that "got touched", Where touched by the linters. since the linters are complaining. 

Let me ask you a question: Do you not see any improvement in this PR ?

**Comment by mlouielu** [comment]
First of all, I'm not here to have a debate with you.

> > "1. ....So, docs/source/conf.py should not be touched."
> 
> A: This is was "touched" by the linter. The linter changed it. Are you saying that your own chosen linter should be used?

Then, we should create another commit or PR. In this case, I would prefer a new PR for this.

> 
> > "2. Before introduce a large change, we need to discuss whether there is a need for this first, for example, what is the need to add file:lineno before each log?"
> 

> A: If I read my description, I will quote myself: "The principle is to have a better way to know which files from the log are doing what, or failing where. .... to debug current issues" ....is this description not clear enough ? I find it that the current logging is like a black box that spits random comments at random times, from random places. Having a file:line, adds more precision.
> 

No, this is not enough, I'll give a +0 or -1 for this PR.

If I really need to know where it failed, I myself as a developer can use `grep` or `ripgrep` to search the source code:

```
➜  guake git:(master) ✗ rg "Spawning new terminal"
guake/notebook.py
393:        log.info("Spawning new terminal at %s", directory)
```

As a developer I didn't find printing filename and line number will help me a lot, also, this PR changes are not clean enough, it need polish and more discussion of its necessity.

> > "3. ... duplicate code,..."
> 
> A: yes I will like that too. in other languages there is **FILE** **LINE** magical constants, but here in python, I have to import the inspect library. Do you have an idea of how to refactor this to reduce the duplicated code? If you can come if the function that will deliver the filename and line number, correctly, I will expend another 6 hours renaming all the logger. functions.

If you don't know, then ask us or seek others help, this is an open source project, don't show hostile to others.

> 
> > "4.... one commit ...."
> 
> A: ...per file ? are you serious.. It has taken 10 hours to this one change, which is ONE FEATURE. This is only adding better logging, that is it. Any other "files" that "got touched", Where touched by the linters. since the linters are complaining.

No, each commit should be atomic, they should at least separate as I describe above.

If linter is complaining, then first deal with linter, then the feature, not putting them into a huge commit.

I would suggest you learn some git flow & git commit message here we used in Guake:

* https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
* https://chris.beams.io/posts/git-commit/

> 
> Let me ask you a question: Do you not see any improvement in this PR ?

As I said above, If you want me to give my opinion, I would give +0 or -1 for this PR:

* I didn't see how it improve development, and
* It have room to polish in both code and commit:
   - to reduce duplicate code0
   - adding readability to git commit. 

Thanks.

**Comment by zeusintuivo** [comment]
I understand now, why this project is failing, No a single fix gets or improvement gets approved. 
It if it is "not perfect" it will not get fixed. 
I get it. 


> don't show hostile to others.
Where is the hostility, ??? If something, I find the review hostile towards someone that is trying to help. 
You could participate in this branch and add improvements, but instead, seem like you take pleasure in pointing faults. 
"pointing faults" seems the new programmer sickness crawling everywhere, crawling all projects. 

I suggest you take a step back and learn how to be human and learn to talk to others that know less than you, I suggest you learn some leading skills, to be a real leader not just an abusive coder. 

I will not continue participating in this project, with such behaviors from the project leaders.


> Thanks.
What do you mean by "thanks," is that like a passive aggressive micro aggression. I do not understand it.

I simply do not understand these kind of transgressions.

**Comment by Davidy22** [comment]
My word, what happened here? I was only gone for a few days.

The conf.py file just needs to be dropped, it's only autoformatted changes anyways.

There's a lot of function calls that have been touched, this could have been done much faster by just overriding some methods from the guake_logging.py file. We just [subclass the python logger](https://stackoverflow.com/questions/37025119/how-to-override-method-of-the-logging-module) and change the logger in guake_logging.py and we don't have to change the call everywhere else.

Might have been a touch late on getting to this though, there's been some walls of text here

**Pull request closed without merging**
