### PR TITLE
Add --split-vertical and --split-horizontal options

### LINKED ISSUE #1497: Add cli option to split tab
Feature request for two new options:
```
  --split-vertical      Split the selected tab vertically
  --split-horizontal
                        Split the selected tab horizontally
```
I believe this would be very helpful for scripting, as in allowing you to open a predefined set of tabs. For example: 
```
guake -n /home
guake -e 'left_command'
guake --split-horizontal
guake -e 'right_command'
```
I will try submitting a PR very soon, or add it to FeatHub otherwise.

### PR DESCRIPTION
**Pull request by phil294**
Closes #1497

sem-ver: feature

### CODE REVIEW

**Comment by gsemet** [comment]
Thanks !

**Comment by gsemet** [comment]
Sorry for late awake. Can you rebase ?

**Comment by phil294** [comment]
No worries - good to go now?

**Comment by gsemet** [comment]
Sure ! Thanks

**Pull request merged**
