### PR TITLE
Prepare release

### PR DESCRIPTION
**Pull request by gsemet**

### CODE REVIEW

**Comment by mlouielu** [comment]
Please not release, I'm still checking #1548, `terminal.destory()` will finally called `RootTerminalBox.remove_dead_child`, which will called `self.get_notebook().remove_page(page_num)`, adding additional line of `self.remove_page(page_num)` may cause multiple page remove.

**Comment by gsemet** [comment]
Yes do not worry :) just preparing it. I wait for your "go" for the release ;)

**Comment by mlouielu** [comment]
@gsemet Can I also add myself into contributors list in the about.glade? thanks.

**Comment by gsemet** [comment]
Of course !

**Pull request merged**
