### PR TITLE
Add quick open possibility for lines containing `/home/`

### PR DESCRIPTION
**Pull request by langpavel**
image

### CODE REVIEW

**Comment by Stibbons** [comment]
hum, ok for merge, even I would prefer if /anything that exist would be supported...

**Comment by langpavel** [comment]
I also discovered that my code not work with paths containing `-` but I think my regex is correct. Can somebody help with this?

Also I have suggestion for character position capturing in regex, like `path/file:line:char` which is not possible now, but I'm not good in :snake: so I don't try implement it...

**Comment by langpavel** [comment]
@Stibbons on POSIX/Linux systems `/home/` is enough. Matching everything which can be path will be probably too expensive on regex and syscalls. This is reasonable compromise

**Comment by Stibbons** [comment]
Indeed. But every interesting files might not be on /home (/mnt or /media as well for example). Logs from /var, config from /etc, might also be interesting !

**Comment by langpavel** [comment]
@Stibbons Right, we can add very tight distionary to regex, but really, very tight. So in POSIX systems it can be `home` as every developer works on local machine.
Interesting `/` directories: `home`, `root`, `etc`, `var`, `usr`, `opt`, `run`, `tmp`, `mnt`, `media`, `proc`

**Pull request merged**
