### PR TITLE
feat:Make guake use the system default theme

### PR DESCRIPTION
**Pull request by Davidy22**
Detect system theme by default like other gtk programs. Some misc setup/cleanup changes in the fork as well.

### CODE REVIEW

**Comment by gsemet** [comment]
For this on I let you fix the pipeline and switch back to norminal review, merge

**Comment by Davidy22** [comment]
Maybe the travis thing is just there from before, still not going away. I'll fix something on the issues list and see if a new pr still has it.

**Comment by gsemet** [comment]
ok, found it :D

**Comment by mlouielu** [comment]
Seems some black format issue:

https://github.com/Guake/guake/pull/1874/checks?check_run_id=3532130826#step:5:414
```
would reformat /home/runner/work/guake/guake/guake/prefs.py
Oh no! 💥 💔 💥
1 file would be reformatted, 32 files would be left unchanged.
```

**Comment by gsemet** [comment]
`make style` is your friend.

**Comment by mlouielu** [comment]
I've put a separate PR for coding style: #1880

**Comment by Davidy22** [comment]
Oh whoops, left it while it was running because I thought it was going to pass. Well, ran black on this and the other one now, and I'll stick around to check that it passes this time.

**Comment by Davidy22** [comment]
Oh, is there some nonsense I have to do with regenerating the reno file? I'll get to figuring that out

**Comment by Davidy22** [comment]
Some bizarre nonsense where `python setup.py sdist` works before I commit a slug file but breaks after. I'll figure this out eventually

**Comment by Davidy22** [comment]
Alright, figured it out, I just messed up formatting on the slug file

**Comment by mlouielu** [comment]
Can you rebase and check if the coding style may changed by black?

**Comment by Davidy22** [comment]
Changes in one file, fixed up now.

**Comment by gsemet** [comment]
And merged as well !

**Pull request merged**
