### PR TITLE
Add shortcut button to toggle "hide on lose focus" option

### PR DESCRIPTION
**Pull request by pacdouglas**
Hi!

I think this can be useful. Sometimes I need toggle this option and open the "Guake Preferences" all the times... u know? lol. 

Greetings and thanks for your app!

### CODE REVIEW

**Comment by gsemet** [comment]
hum, I am not fan of clutering the main ui...

**Comment by pacdouglas** [comment]
Sample: 
image

**Comment by la5942** [comment]
> hum, I am not fan of clutering the main ui...

I agree, also not something that all users would want. @pacdouglas Why not use the keyboard shortcut instead of adding unnecessary clutter? `Ctrl+F1`

**Comment by pacdouglas** [comment]
Yeah, I didn't know the shortcut, and on master branch we have a new button to navigate between the tabs, so I was inspired by this buttons. 

But you're right, less is more, I'll close the PR.

**Pull request closed without merging**
