### PR TITLE
Fixed typo on Man page

### PR DESCRIPTION
**Pull request by jschwanebeck**
guake.1

Line 20: Dioplay -> Display

### CODE REVIEW

**Comment by pypingou** [comment]
Did you fix the right file?
I'm seeing the change as if you are adding a whole new file, instead of just patching this one: https://github.com/Guake/guake/blob/master/data/guake.1

**Comment by Stibbons** [comment]
ok look good

**Comment by pypingou** [comment]
So we now have 2 man pages?
https://github.com/Guake/guake/blob/master/data/guake.1
https://github.com/Guake/guake/blob/master/guake.1
...

**Comment by Stibbons** [comment]
weird indeed

**Comment by pypingou** [comment]
There is nothing weird, see my first comment, @jschwanebeck added a new file instead of correcting the existing one...

**Pull request merged**
