### PR TITLE
Fix CI failure of PR #1989

### PR DESCRIPTION
**Pull request by jcfstabile**
Downgrade pipenv to 2021.5.29

### CODE REVIEW

**Review by mlouielu — CHANGES_REQUESTED** [review]
Your local branch should rebase with Guake/master. The git commits are not clean.

**Review by mlouielu — CHANGES_REQUESTED** [review]
I believe commits still have problem, we should only get one commit log in this case.

The easiest way may be copy the hash (cf94936e8d48f5314fca382e459cd665e7aec4ad), reset to latest main hash, then cherry-pick the copied hash back.

**Comment by jcfstabile** [comment]
So, to be on same page you propose:
git reset 3230199
git cherry-pick cf94936
git push

**Comment by mlouielu** [comment]
> So, to be on same page you propose:
> 
> git reset [3230199](https://github.com/Guake/guake/commit/32301994813de64134200e0512ee3614eae7f66f) git cherry-pick [cf94936](https://github.com/Guake/guake/commit/cf94936e8d48f5314fca382e459cd665e7aec4ad) git push
> 
> am I right?

* git reset --hard HASH
* ...
* git push --force

You can check it with your `git log`, it should look like this:

```
commit 1b6918175a06b614e7f9462b0c18c11a5548eaf7 (HEAD -> pr_1990)
Author: Juan Carlos Francisco Stabile <jcfstabile@gmail.com>
Date:   Wed Dec 15 22:36:20 2021 -0300

    Downgrade pipenv version to 2021.5.29

commit 32301994813de64134200e0512ee3614eae7f66f (origin/master, origin/HEAD, master)
Author: Juan Carlos Francisco Stabile <jcfstabile@gmail.com>
Date:   Tue Dec 14 23:30:02 2021 -0300

    Add release note for bugfix on issue #1971

```

**Comment by jcfstabile** [comment]
Good. Thank you.

**Comment by Davidy22** [comment]
I don't have much of an issue with squashing to clean up commits, but it looks like CI is still failing. Error message:

```
Error: the command pytest could not be found within PATH or Pipfile's [scripts].
```

I remember hitting this one in my own endeavors to fix CI for pypi. [My change in .github/workflows/ci.yml](https://github.com/Davidy22/guake/commit/abcedf4ac96a798891a9035d0a576a42144bac01) adding `pytest pytest-cov pyfakefs` to the pip install resolved this for me I think, I might have done some other things on top of that but it was a while ago now.

**Comment by Davidy22** [comment]
If it helps, you could cherry pick my changes, but I have a lot of scratch work in my repo and you might just be better off copying things where they might look relevant

**Comment by gsemet** [comment]
Can you give a try with poetry ?

**Comment by gsemet** [comment]
upgrading pipenv is not possible (setuptools, ...). Using poetry will fix this issue

**Pull request closed without merging**
