### PR TITLE
Update news file

### PR DESCRIPTION
**Pull request by Davidy22**
Prep for release

### CODE REVIEW

**Comment by Davidy22** [comment]
@mlouielu This and a bunch of other PRs have been sitting for two weeks, can they get looked at eventually?

@gsemet can we get the maintainer transition progressed a little bit? Commits get deadlocked for weeks because we can't merge our own work, and a litany of external tools still need to be troubleshot by telegraph because we can't access them. How's the progress on readthedocs?

**Comment by gsemet** [comment]
Hi. You are pretty much autonomous on the review and merge of the patches, I do not see what you would like more ? I can pass you as administrator of the site so you can merge your patches after a few days without reviews.
Most of the time I do not get the notification so you need to @ me manually or I do not see the MR…
For the release process, you (both of you actually) need to rework it and improve it.

**Comment by gsemet** [comment]
Admin permission granted

**Comment by Davidy22** [comment]
The main peeve was waiting indeterminate amounts of time for my code changes to get merged or just responded to making it difficult to actively work on Guake. Thanks for the permissions, @mlouielu may need them too if I go absentee because he can't get anything into the code either without a reviewer.

Been throwing attempts at the automated release process periodically, you can see where I'm at and my prior output [here](https://github.com/Davidy22/guake/tree/fixci), if anyone's got it figured out I'm very interested in seeing what they got.

**Comment by gsemet** [comment]
With poetry and poetry-dynamic-versioning, things are easier. It replaces pipenv and pbr, so package are more « standard ».
The good added value would be to have a complete release triggered on a single tag (without the need to update manually the release note,…). For example we put a tag and the release pipeline use the GitHub api to put the release description. We simply edit it after and add a little intro…

**Comment by Davidy22** [comment]
Getting fairly tempted to do the poetry switch to try solve this, will try that if I still can't make it work.

**Comment by Davidy22** [comment]
So I am getting a little frustrated with this, but it's more to do with pytest really than pipenv I think. Might give it a rest till my next attempt, but all my failed runs are probably visible on my branch

**Pull request merged**
