### PR TITLE
Cleanup and enable highly useful flake8 checks

### PR DESCRIPTION
**Pull request by eli-schwartz**
Unused imports and code used without importing it, is quite useful to know about and fix. Stop ignoring those checks, and fix all current issues.

```
 23 files changed, 17 insertions(+), 142 deletions(-)
```

### CODE REVIEW

**Review by Davidy22 — CHANGES_REQUESTED** [review]
Hello,

The changes here I assume are flake detect dead code and imports, so I'm alright with folding this in. We've done some updates to fix our CI since this patch was created. so I just need you to do an update and make sure your changes pass CI. Would be nice if you could squash similar commits down maybe.

**Comment by Davidy22** [comment]
I'm going to drop the gettext commit because it fails test cases, but you can recreate the change as a new pull request in the future in a patch that passes the build.

**Comment by eli-schwartz** [comment]
Why do you review my PR and ask for changes, then immediately go ahead and push your own changes to my PR which try... and fail... to do so?

Your change broke the CI on my gettext patch and there is an obvious fix, and now you want to drop that change without even waiting a couple hours for me to show up?

Look, I know you're probably impatient to merge changes which people have contributed months ago without response. But you could give people a couple hours to reply without immediately concluding that that they've lost interest and won't return to address your review comments, then force pushing to delete commits that you are apparently meh about.

Keeping in mind also that it's rather annoying to actually re-aquire a copy of the commit after you've deleted it from my branch and github doesn't expose it visibly past a force push, if I don't have it locally backed up...

Perhaps you're trying to *make* me lose interest and disappear never to return?

I normally leave "allow edits by maintainers" checked as a good faith gesture so that maintainers can do things like rebase or add additional commits, this is the first time I've ever had someone delete them before. Perhaps I should rethink that policy.

**Comment by Davidy22** [comment]
Oh whoops, went ahead with going through and dealing with the things that didn't pass checks myself a day after the initial review. I think I can restore the gettext change for fixing, should still be in my reflog.

**Comment by Davidy22** [comment]
Still needs amending though, the test suite doesn't pick up on the builtin when checking the prefs file, after this there's a recent black update that needs a rebase to check.

**Comment by eli-schwartz** [comment]
Thank you.

One of your CI fixes involved adding another locale.gettext import, which meant that it was being imported globally (your addition) and in `__main__` (my addition) and then raised a lint error for double import.

The remaining issues were black, plus the test suites not running with gettext patched into builtins. This would be a bit simpler if I wanted to import locale and patch builtins in `guake/__init__.py` but I refrained from doing so because this would add a new import to `guake/guake_toggle.py` which is supposed to be as fast as possible, so I instead added it at every script entry point.

**Comment by eli-schwartz** [comment]
Alright, CI passed. \o/

**Review by Davidy22 — APPROVED** [review]
Alright, changes look fine and it passes tests, merging.

**Pull request merged**
