### PR TITLE
Resolves #614 Reset terminal shorcut

### LINKED ISSUE #614: "Reset terminal" shortcut
It would be nice to have the ability to assign a keyboard shortcut to "Reset terminal" (#608) menu entry.

### PR DESCRIPTION
**Pull request by thardev**

### CODE REVIEW

**Comment by Stibbons** [comment]
thanks a lot

**Comment by thardev** [comment]
Hello @Stibbons my last commit was about resolving this issue #598 I added a new file, a SVG image, because this fixes that issue, but later, after doing the commit, I noticed that when I try to install Guake it fails because the SVG file isn't added to the correct folder, did you tried to install? If you face that problem, do you know how to add the new file? I don't know so much about building with Autotools...
Sorry of that. Cheers

**Comment by Stibbons** [comment]
Hello. I had to revert in new version 0.8.3. I don't have much time to fix the proper usage of the svg file, I think it is related to the makefile.in. I try to fix it next week

**Comment by thardev** [comment]
Ok, thank you so much @Stibbons, tomorrow I'll try to fix it and I'll do the pull request for #598 :smiley:

**Pull request merged**
