### PR TITLE
Add manjaro installation section

### LINKED ISSUE #1429: Documentation Update: Installing on manjaro
As per the request for info on the docs [https://guake.readthedocs.io/en/stable/user/installing.html](url) I was able to install Guake on Manjaro Gnome version 17.1.12 by simply executing this: 

pacman -S guake 

This should would on any arch-based distro with pacman installed (which is likely installed by default).

### PR DESCRIPTION
**Pull request by Davidy22**
Turning a quick contribution that someone had into a pull request.

Is copied from and resolves #1429

### CODE REVIEW

**Comment by mlouielu** [comment]
LGTM, we can also consider to put with `Arch`.

**Comment by Davidy22** [comment]
Manjaro's supposed to be the easy version of arch, I would hesitate to claim that instructions for manjaro also work on arch without testing.

**Comment by gsemet** [comment]
approved

**Review by gsemet — APPROVED** [review]

**Comment by gsemet** [comment]
You should both have approval permission, so you can merge these pull request yourself :D

**Comment by Davidy22** [comment]
can't approve my own pr, I can only expedite other people

**Pull request merged**
