### PR TITLE
PRs combined 

### PR DESCRIPTION
**Pull request by zeusintuivo**
If you are like and would like to see the lastest PR's working in your machine, and you can and know how to compile it. Then I this PR is for you!, Just check out "prs_combined" and compile your project again. I have taken the effort of running the linters and passing the tests. Making sure it compiles and runns
```bash 
guake --quit                                                     # incase is running in the background
kill $(pgrep guake)                                              # incase is running in the background
git remote add zeusintuivo git@github.com:zeusintuivo/guake.git  # Add me repo
git fetch zeusintuivo 
git pull zeusintuivo prs_combined
git checkout prs_combined                                        # Check out me branch
source env/bin/activate     # Go into your virtualenv environment
make
sudo make dev               # build with sudo to warranty a clean build
source deactivate           # Get out of your virtualenv environment
sudo make install           # install with sudo to replace your current executables
guake                       # run ! 
guake --verbose             # or in case you also want to see what is going on.
```

Please follow these steps before submitting a new Pull Request to Guake:

- rebase on latest HEAD:

  ```bash
  $ git pull --rebase upstream master
  ```

- hack your change

- to execute the code styling, checks and unit tests:

  ```bash
  $ make style check reno-lint test
  ```

- describe your change in a slug file for automatic release note
  generation, using:

  ```bash
  $ make reno SLUG=<short_name_of_my_feature>
  ```

  and edit the created file in `releasenotes/notes/`.
  You can see how `reno` works using `pipenv run reno --help`.

  Please use a generic slug (eg, for translation update,
  use `translation`, for bugfix use `bugfix`,...)

- create new commit message

  ```bash
  $ <hack the code>
  $ git commit --all
  ```

- If your change is related to a GitHub issue, you can add a reference
  using `#123` where 123 is the ID of the issue.
  You can use `closes #123` to have GitHub automatically close the issue
  when your contribution get merged

- Semantic commit is supported (and recommended). Add one of the following
  line in your commit messages:
  
  ```
  # For a bug fix, uses:
  sem-ver: bugfix
  
  # For a new feature, uses:
  sem-ver: feature
  
  # Please do not use the 'breaking change' syntax (`sem-ver: api-break`), 
  # it is reserved for really big reworks
  ```

### CODE REVIEW

**Comment by gsemet** [comment]
I think we will close this MR that is too old and has many conflict. Any objection?

**Comment by Davidy22** [comment]
This was never really a pull request anyways, more like a showcase of a branch and now that we have a [discussion forum](https://github.com/Guake/guake/discussions) that might be a better place to host the advertisement of this branch than the pull request queue.

**Comment by Davidy22** [comment]
Actually yeah, since this pr isn't actually supposed to be a pull request, and we have a discussion forum tab now, I'm going to close this so you can make a thread on the forums to feature your branch. A lot of conflicting changes between last change to this and now.

**Comment by zeusintuivo** [comment]
started merging from master. not all changes from this branch are just "old" there are lots of improvements that are getting ignored. I will continue to merge master tomorrow into it.

**Comment by Davidy22** [comment]
For some number of the changes a version of them may have already been merged into master, might need to drop some amount of commits because of an equivalent, colliding change in master. Since this branch is supposed to be a check this out and try it kind of thing and not a merge this affair, we have a [discussion forum](https://github.com/Guake/guake/discussions) that may be a better place to showcase it now that we have it. For your other pr, most of the improvements are just already addressed and only generate merge conflicts with main now, the other pr needs to be reformed or recreated as just the one fix that hasn't been done yet in master.

**Pull request closed without merging**
